name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tooling
        run: |
          pip install detect-secrets checkov pip-audit build
          cargo install cargo-audit --locked || true
          cargo install cargo-tarpaulin --locked || true
          go install golang.org/x/vuln/cmd/govulncheck@latest || true
      - name: Generate protos
        run: make proto
      - name: Build all
        run: make rust go python
      - name: Run tests & coverage
        env:
          COVERAGE_MIN: 70
        run: make test || true
      - name: Coverage gate enforce
        env:
          COVERAGE_MIN: 70
        run: bash scripts/coverage_gate.sh
      - name: Security aggregate
        run: make security || true
      - name: detect-secrets scan
        run: detect-secrets scan || true
      - name: Checkov IaC scan
        run: checkov -d infra || true
      - name: Mock cosign sign
        run: echo "cosign sign mock/image:tag (placeholder)"
      - name: SBOM placeholder
        run: echo "SBOM diff placeholder"
