name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo build
        run: |
          for d in services/*/Cargo.toml; do (cd $(dirname $d) && cargo build --quiet); done
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Go build
        run: |
          for d in services/*/go.mod; do (cd $(dirname $d) && go build ./...); done
  build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Validate pyproject services
        run: |
          pip install build >/dev/null
          for d in services/*/pyproject.toml; do (cd $(dirname $d) && python -m build >/dev/null || echo "build failed: $d"); done
