name: nightly-perf

on:
  schedule:
    - cron: '0 2 * * *'  # 02:00 UTC daily
  workflow_dispatch: {}

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
      - name: Install extras (gnuplot)
        run: |
          sudo apt-get update -y && sudo apt-get install -y gnuplot
      - name: Run perf update script
        env:
          PERF_REGRESSION_PCT: 12
        run: |
          chmod +x scripts/update_perf_baseline.sh
          ./scripts/update_perf_baseline.sh || true
      - name: Generate sparkline badges
        run: |
          chmod +x scripts/generate_perf_sparkline.sh
          ./scripts/generate_perf_sparkline.sh || true
      - name: Run detection overhead bench
        run: |
          cargo bench --bench detection_overhead --no-default-features 2>&1 | tee bench-detection.txt || true
      - name: Upload detection bench artifact
        uses: actions/upload-artifact@v4
        with:
          name: detection-bench
          path: bench-detection.txt
      - name: Upload regression artifact
        uses: actions/upload-artifact@v4
        with:
          name: perf-regressions
          path: target/perf-regressions.json
      - name: Commit trend (if changed)
        run: |
          git add docs/perf-sparkline.svg docs/perf-*.svg 2>/dev/null || true
          if git diff --quiet docs/perf-trend.csv docs/perf-baseline.md docs/perf-sparkline.svg; then
            echo "No perf doc changes."; exit 0; fi
          git config user.name 'perf-bot'
          git config user.email 'perf-bot@users.noreply.github.com'
          git add docs/perf-trend.csv docs/perf-baseline.md docs/perf-sparkline.svg docs/perf-*.svg || true
          git commit -m 'chore(perf): nightly benchmark update' || true
          git push || true
