name: security-extended

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  rust-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-audit
        run: cargo install cargo-audit || true
      - name: Run cargo audit
        run: cargo audit --json || cargo audit || true

  go-govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run govulncheck on modules
        run: |
          for mod in $(find services -maxdepth 2 -name go.mod -printf '%h\n'); do \
            echo "[govulncheck] $mod"; \
            (cd $mod && govulncheck ./... || true); \
          done

  python-pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Run pip-audit
        run: |
          for proj in $(find services -maxdepth 2 -name pyproject.toml -printf '%h\n'); do \
            echo "[pip-audit] $proj"; \
            (cd $proj && pip-audit || true); \
          done
